---
- name: ConfigBGP
  hosts: RS-HCM-01
  tasks:
  - name: ConfigBGP
    ios_config:
      parents: router bgp 1000
      lines:
        - neighbor 210.10.14.14 remote-as 100
        - neighbor 210.10.10.118 description Peerv4-ASN-118
        - neighbor 210.10.10.118 version 4
