---
- name: BGP
  hosts: RS-HCM-01
  tasks:
  - name: showBGP_Summary
    ios_command:
      commands:
        - show ip bgp summary
    register: show_ip
  - debug: var=show_ip.stdout_lines
#cac lenh phai dung tren cisco