---
- name: test
  hosts: all
  tasks:
  - name: showInterface
    ios_command:
      commands:
        - show ip int brief
    register: show_ip
  - debug: var=show_ip.stdout_lines
#cac lenh phai dung tren cisco
