---
- name: Config_IPInterface
  tasks:
  - name: interfaceIPaddress
    ios_config:
      parents: interface Ethernet0/1
      lines:
        - des VNIX
        - no ip address
        - ip address 210.10.10.1 255.255.255.0
        - no shutdown
        - duplex full
  - name: showInterface
    ios_command:
      commands:
        - show ip int brief
    register: show_ip
  - debug: var=show_ip.stdout_lines
#cac lenh phai dung tren cisco
