---
- name: BGP
  hosts: RS-HCM-01
  tasks:
    - name: ConfigBGP
      ios_bgp:
        config:
          bgp_as: 1000
          log_neighbor_changes: true
          neighbors:
          - neighbor: 210.10.14.14
          remote_as: 100
          address_family:
          - afi: ipv4
            safi: unicast
          neighbors:
          - neighbor: 210.10.14.14
          activate: yes
          maximum_prefix: 5000
