---
- name: ConfigBGP
  hosts: RS-HCM-01
  tasks:
  - name: ConfigBGP_Session
    ios_config:
      parents: router bgp 1000
      lines:
        - neighbor 210.10.14.14 remote-as 100
        - neighbor 210.10.14.14 description Peerv4-ASN-14
        
