---
- name: Interface
  hosts: RS-HCM-01
  tasks:
  - name: showRunInterface
    ios_command:
      commands:
        - show run interface
    register: show_run
  - debug: var=show_run.stdout_lines
#cac lenh phai dung tren cisco
